# Generated by Django 5.0 on 2023-12-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_app', '0002_translation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
